# Generated by Django 3.0.7 on 2020-06-07 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='WikiUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiki_user_id', models.CharField(max_length=32, unique=True)),
                ('wiki_user_text', models.CharField(max_length=32)),
                ('wiki_user_is_bot', models.BooleanField(default=False)),
                ('wiki_user_registration_dt', models.DateTimeField()),
                ('wiki_user_groups', models.ManyToManyField(null=True, to='wiki_api.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_uri', models.CharField(max_length=500)),
                ('page_wiki_id', models.CharField(max_length=64, unique=True)),
                ('page_wiki_id_num', models.IntegerField(unique=True)),
                ('page_title', models.CharField(max_length=250)),
                ('page_creation_timestamp', models.DateTimeField()),
                ('page_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki_api.Domain')),
            ],
        ),
    ]
