# Generated by Django 3.0.7 on 2020-06-07 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wiki_api.WikiUser'),
        ),
        migrations.AlterField(
            model_name='wikiuser',
            name='wiki_user_groups',
            field=models.ManyToManyField(to='wiki_api.Group'),
        ),
    ]
