# Generated by Django 3.0.7 on 2020-06-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki_api', '0002_auto_20200607_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikiuser',
            name='wiki_user_groups',
            field=models.ManyToManyField(null=True, to='wiki_api.Group'),
        ),
    ]
