# Generated by Django 3.0.7 on 2020-06-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki_api', '0007_auto_20200612_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikiuser',
            name='wiki_user_id',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
    ]
