
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    project: local
  labels:
    name: drf-wiki-api
  name: drf-wiki-api
  namespace: local
spec:
  selector:
    matchLabels:
      name: drf-wiki-api
  template:
    metadata:
      annotations:
        project: local
      labels:
        name: drf-wiki-api
      namespace: local
    spec:
      restartPolicy: Always
      containers:
      - name: drf-wiki-api
        image: drf-wiki-api:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_NAME
          value: "django_db"
        - name: DB_USER
          value: "django"
        - name: DB_PASSWORD
          value: "django123"
        - name: DB_HOST
          value: "drf-wiki-db"
        - name: DB_PORT
          value: "5432"
        ports:
        - containerPort: 8090
        volumeMounts:
        - mountPath: /api
          name: drf-wiki-api-claim0
      volumes:
      - name: drf-wiki-api-claim0
        hostPath:
          path: %{REPO_PATH}%/src/api
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    project: local
  name: drf-wiki-api
  namespace: local
spec:
  ports:
  - name: "8090"
    port: 8090
    targetPort: 8090
    nodePort: 8090
  selector:
    name: drf-wiki-api
  type: NodePort


---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    project: local
  labels:
    name: drf-wiki-db
  name: drf-wiki-db
  namespace: local
spec:
  selector:
    matchLabels:
      name: drf-wiki-db
  template:
    metadata:
      annotations:
        project: local
      labels:
        name: drf-wiki-db
        app: postgres
      namespace: local
    spec:
      restartPolicy: Always
      containers:
      - name: drf-wiki-db
        image: postgres:9.6
        imagePullPolicy: IfNotPresent
        env:
        - name: POSTGRES_DB
          value: "django_db"
        - name: POSTGRES_USER
          value: "django"
        - name: POSTGRES_PASSWORD
          value: "django123"
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgredb
            subPath: postgres
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: drf-wiki-db-claim0
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    project: local
  name: drf-wiki-db
  namespace: local
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    name: drf-wiki-db
  type: NodePort
